### PR TITLE
Paypal id settings

### PR DESCRIPTION
**Pull request by jonparker**
@qdozaq I hope I'm on the right track with this.
This is just a draft to make sure I don't go down the wrong path.

### CODE REVIEW

**Comment by qdozaq** [comment]
Looks good so far. Obviously up for design to figure out, but we'll probably want something similar to the userprofile page where you can edit and save info which is sent to firebase

**Comment by jonparker** [comment]
Ok, makes sense. I'll have a look at user profile as a reference.

**Comment by jwu910** [comment]
Is this still being worked on?

**Comment by qdozaq** [comment]
Nah we can close this

**Pull request closed without merging**
