### PR TITLE
Addresses #260 -- seed db every 2 hours

### PR DESCRIPTION
**Pull request by rainrivas**
Addresses #260 
Creating a workflow (`seed.yml`) to fill our firebase with new data every 2 hours. 
**NOTE** The script will fail until `FIREBASE_SECRET` has been added to repo. I think @mat10tng  has already done this, but adding him on here to confirm

### CODE REVIEW

**Comment by rainrivas** [comment]
Check error seems to be due to the node step on the CI not correctly downloading nodejs 

Use Node.js 10.x
32s
```
##[error]connect ETIMEDOUT 104.20.23.46:443
Run actions/setup-node@v1
  with:
    node-version: 10.x
    always-auth: false
##[error]connect ETIMEDOUT 104.20.23.46:443
```
If there is some way to rebuild it I'm sure it will pass

**Comment by jwu910** [comment]
Re-ran the check

**Comment by jwu910** [comment]
Accidentally closed the PR sorry. Finger slipped.

Was going to comment and ask, are the permissions set up to allow CI to write to the DB to re-seed with this job?

**Comment by utunga** [comment]
lemme know if i can help?

**Comment by azmainamin** [comment]
This looks good to me. I approved but I'd like someone with more knowledge of this to merge it in.

**Comment by rainrivas** [comment]
@azmainamin so the seed.yml will install dependencies required to run the python script that @mat10tng wrote as mock data. 
It will also install the npm module for firebase and set the auth token using github secrets.  It then calls the node script Tuan wrote to publish our fake data to firebase.
@jwu910 the CI doesn't really write anything; it's the user in the secret that Tuan added as part of github secret in admin settings. The update happens via a POST call from what I'm gathering
```

async function upload(data, path) {
  return await admin
    .firestore()
    .doc(path.join("/"))
    .set(data)
    .then(() => console.log(`Document ${path.join("/")} uploaded.`))
    .catch(() => console.error(`Could not write document ${path.join("/")}.`));
}
```

**Pull request merged**
