### PR TITLE
Add react-app polyfill for ie9 and ie11 into index.tsx, patching last fix for ie support

### PR DESCRIPTION
**Pull request by CSumm**
This PR fixes compatibility issues with IE11, allowing the application to run on the browser.
Relates to issue #339 and closed PR #340

### CODE REVIEW

**Comment by jwu910** [comment]
Can we use browserslist to attempt to build for latest IE build and not use polyfills? CRA should be reading the brwoserslist and adjust the builds accordingly as much as possible. 

If we lose some functionality on latest IE, we may just want to have that discussion about not supporting it should some of the features be not worth the time

**Comment by CSumm** [comment]
I reread the create-react-app documentation once more and under the browserlist example, there's an info section stating that we would need polyfill support as well as adding to browserlist: https://create-react-app.dev/docs/supported-browsers-features/#configuring-supported-browsers. This can be found near the end of the page.

This means that to support IE, polyfills are necessary it seems.

**Comment by jwu910** [comment]
I haven't checked any of this on windows yet @CSumm.
But yeah reading through the docs you've shared it seems so. I would look to checking in with the team to have that discussion if ie11 is something we want to support or just direct users to installing one of the modern browsers.

Looking at some of the polyfill required features, we are using a couple of them.

**Comment by CSumm** [comment]
Sounds like a good idea and wait for more opinions on this. For now, we could put this PR on the back burner.

**Pull request closed without merging**
